{% set name = "sysstat" %}
{% set version = "12.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sysstat/sysstat/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dc77a08871f8e8813448ea31048833d4acbab7276dd9a456cd2526c008bd5301

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - autoconf
  host:

test:
  commands:
    - sar --help
    - sadf -V
    - iostat
    - tapestat -V
    - mpstat
    - pidstat
    - cifsiostat

about:
  home: http://sebastien.godard.pagesperso-orange.fr/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Performance monitoring tools for Linux
  description: |
    The sysstat package contains various utilities, common to many commercial
    Unixes, to monitor system performance and usage activity:

     * iostat reports CPU statistics and input/output statistics for block devices and partitions.
     * mpstat reports individual or combined processor related statistics.
     * pidstat reports statistics for Linux tasks (processes) : I/O, CPU, memory, etc.
     * tapestat reports statistics for tape drives connected to the system.
     * cifsiostat reports CIFS statistics.

  doc_url: http://sebastien.godard.pagesperso-orange.fr/documentation.html
  dev_url: https://github.com/sysstat/sysstat

extra:
  recipe-maintainers:
    - chrisburr
